### ISSUE TITLE
Jep command

### ISSUE THREAD

**Issue by Toby-Larone** [JVMRally/Lambda#4]
get by id with `--id`
get by keyword search with `-s` or `--search`
filter with `--status X`, `--release 14` 

usage: 
`!jep --id 347` -- return jep 347
`!jep --search switch` - return all jeps with title containing "switch"
`!jep --search "garbage collector"` - return all jeps with title including "garbage collector"
`!jep --status draft` - return all draft jeps
`!jep --release 14` - return all jeps targetted for jdk14
`!jep --type process` - return all process type jeps
`!jep --search "switch expressions" --release 12` - return jeps with title containing "switch expression" for release 12

**Comment by lmilunovic** [comment]
Assign to me, will try to do it.

**Comment by lmilunovic** [comment]
#8 Implemented JEP command.
